---
### Site metadata ###

site_name: Logistro
site_description: Logistro is a simple wrapper for logging
site_url: https://github.com/geopozo/logistro
repo_url: https://github.com/geopozo/logistro
repo_name: geopozo/logistro
edit_uri: edit/main/docs/


### Build settings ###

docs_dir: 'docs/'
nav:
  - Home: 'README.md'
  - $api/logistro.***
theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.sections
extra_css:
  - style.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - mkapi:
      enabled: true
      debug: true
