---
### Site metadata ###

site_name: logistro
repo_name: github


### Build settings ###

docs_dir: 'docs/'
nav:
  - Readme: >-
      {
        "dest": "README.md",
        "src": "../README.md",
        "replace": {"src='docs/": "src='"}
      }
  - Note: >-
      {
        "dest": "TECH_NOTE.md",
        "src": "../TECH_NOTE.md",
        "replace": {"src='docs/": "src='"}
      }
  - API:
      - >-
        {
          "api": "logistro",
          "tree": "imports"
        }
      #  - APIPKG: >-
      #{
      #  "api": "logistro",
      #  "tree": "packages"
      #}
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - quimeta
  - quicopy
  - quiapi
